spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movies
    data-username: root
    data-password: F3lip30s0ri0
    
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration